<form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
    <input type="hidden" name="cmd" value="_donations" />
    <input type="hidden" name="business" value="HJFN6NRBH6XXW" />
    <input type="hidden" name="currency_code" value="EUR" />
    <input type="hidden" name="amount" value="1" />
    <input type="hidden" name="return" value="https://originea-c05b6.web.app/?ref=XY" />
    <input type="image" src="https://www.paypalobjects.com/en_US/CH/i/btn/btn_donateCC_LG.gif" border="0" name="submit" title="PayPal - The safer, easier way to pay online!" alt="Donate with PayPal button" />
    <img alt="" border="0" src="https://www.paypal.com/en_CH/i/scr/pixel.gif" width="1" height="1" />
</form>